language: cpp
dist: trusty
sudo: true

branches:
  only:
    - master
    - working


matrix:
  include:

    - os: linux
      env:
        - TEST="Clang"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang
            - gcc
            - g++
      compiler: clang
      script:
        - cmake CMakeLists.txt
        - make
        - make IZ2

    - os: linux
      env:
        - TEST="UnitTest"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang
            - gcc
            - g++
      compiler: clang
      script:
        - cmake CMakeLists.txt
        - make
        - ctest

    - os: linux
      env:
        - TEST="Valgrind"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
            - gcc
            - g++
            - valgrind
      compiler: clang
      script:
        - cmake CMakeLists.txt
        - make
        - IZ2 -T memcheck

    - os: linux
      env:
        - TEST="Codecov"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
            - gcc
            - g++
      compiler: clang
      script:
        - cmake -DENABLE_COVERAGE=ON
        - make
        - make IZ2
        - cd ..
        - bash <(curl -s https://codecov.io/bash)


after_success:
  - bash <(curl -s https://codecov.io/bash)